#!/bin/sh

set -e -u

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

export TMPDIR=${TMPDIR:-/tmp}
payload=$(mktemp $TMPDIR/stopover-resource-request.XXXXXX)

cat > $payload <&0

uri=$(jq -r '.source.uri // ""' < $payload)
username=$(jq -r '.source.username // ""' < $payload)
password=$(jq -r '.source.password // ""' < $payload)
team=$(jq -r '.source.team // ""' < $payload)

wget --no-check-certificate "${uri}/api/v1/cli?arch=amd64&platform=linux" -O fly

chmod +x fly

./fly --target ci \
  login \
  --insecure \
  --concourse-url "${uri}" \
  --username "${username}" \
  --password "${password}" \
  --team-name "${team}"

ATC_BEARER_TOKEN=$(yq r ~/.flyrc 'targets.ci.token.value')
export ATC_BEARER_TOKEN

stopover "${uri}" "${BUILD_TEAM_NAME}" "${BUILD_PIPELINE_NAME}" "${BUILD_JOB_NAME}" "${BUILD_NAME}" > versions.yml

jq -n \
  --arg build_id "${BUILD_ID}" \
  --arg versions "$(yq read --tojson versions.yml)" \
  '{
    "version": { "build_id": $build_id },
    "metadata": [
        { "name": "versions", "value": $versions }
    ]
  }' >&3
